CREATE TABLE VENDOR (
    VENDOR_ID CHAR(10) PRIMARY KEY,
    VENDOR_NAME VARCHAR(50),
    VENDOR_ADDRESS VARCHAR(75),
    VENDOR_CITY VARCHAR(50),
    VENDOR_STATE VARCHAR(50),
    VENDOR_ZIP CHAR(9),
    VENDOR_POC VARCHAR(50),
    VENDOR_PHONE VARCHAR(13),
    PAYMENT_TYPE VARCHAR(50),
    VENDOR_BANK VARCHAR(50),
    VENDOR_EIN CHAR(9),
    );

CREATE TABLE PARTS (
   PART_ID CHAR(14) PRIMARY KEY,
   VENDOR_ID CHAR(10),
   PART_DESC VARCHAR(30),
   UNIT_COST DECIMAL(19,4),
   PARTS_STATUS CHAR(1),
   FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID CHAR(20),
    PRODUCT_DESC VARCHAR(50),
    DATE_OF_MAN DATE,
    SHIP_STATUS CHAR(1),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PARTSOFPRODUCT (
    PRODUCT_ID CHAR(20),
    PART_ID CHAR(14),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (PART_ID) REFERENCES PARTS(PART_ID),
    PRIMARY KEY (PRODUCT_ID, PART_ID)
);

CREATE TABLE EMPLOYEE (
      EE_ID CHAR(4),
      EE_FNAME VARCHAR(20),
      EE_LNAME VARCHAR(20),
      EE_SOCSEC CHAR(9),
      EE_ADDRESS VARCHAR(50),
      EE_STATE CHAR(2),
      EE_CITY VARCHAR(20),
      EE_ZIP CHAR(9),
      EE_PHONENUM CHAR(10),
      EE_DEPT VARCHAR(20),
      PRIMARY KEY (EE_ID)
);

CREATE TABLE CUSTOMER (
      CUS_NUM CHAR(10),
      CUS_NAME VARCHAR(30),
      CUS_BILL_STREET VARCHAR(50),
      CUS_BILL_CITY VARCHAR(50),
      CUS_BILL_STATE CHAR(2),
      CUS_BILL_ZIP CHAR(9),
      CUS_BILL_POC VARCHAR(50),
      CUS_BILL_PHONE CHAR(10),
      CUS_BILL_EMAIL VARCHAR(50),
      CUS_SHIP_STREET VARCHAR(50),
      CUS_SHIP_CITY VARCHAR(50),
      CUS_SHIP_STATE CHAR(2),
      CUS_SHIP_ZIP CHAR(9),
      CUS_SHIP_POC VARCHAR(50),
      CUS_SHIP_PHONE CHAR(10),
      CUS_SHIP_EMAIL VARCHAR(50),
      PRIMARY KEY (CUS_NUM)
);

CREATE TABLE PAYROLL (
     PAY_ID CHAR(4),
     EE_ID CHAR(4),
     EE_PAY_TYP1 CHAR(1),
     EE_PAY_TYP2 CHAR(1),
     MINUTES_WORKED INT,
     DATE_WORKED DATE,
     PRIMARY KEY (PAY_ID),
     FOREIGN KEY (EE_ID) REFERENCES EMPLOYEE(EE_ID),
);

CREATE TABLE SALE (
      PO_NUM CHAR(3),
      CUS_NUM CHAR(10),
      EE_ID CHAR(4),
      SALES_UNITS INT,
      SALE_PRICE DECIMAL(19,4),
      SALE_DATE DATE,
      PRIMARY KEY (PO_NUM),
      FOREIGN KEY (CUS_NUM) REFERENCES CUSTOMER(CUS_NUM),
      FOREIGN KEY (EE_ID) REFERENCES EMPLOYEE(EE_ID)
);






